version: "3.7"
services:
  betteraiapp:
    container_name: public
    build:
      context: .
      # dockerfile: dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3001:5173"
    env_file:
      - ./.env
